export const DefaultSetting = {
    // not need setting
    DEFAULT_CACHE_SETTING: 3600,
    // setting
    SUITABLE_THRESHOLD: 3600, //%
    DEFAULT_SEARCH_DISTANCE: 5000, //m
    MAX_OVERTIME_EXPIRED: 23,
    MAPPING_WORKING_TIME_PERCENT: 70,
    DEFAULT_AVATAR: 'https://i.pinimg.com/564x/d4/52/8c/d4528cf9df9468474fa54fd9919edf41.jpg',
};

export const SettingNames = {
    MAX_OVERTIME_EXPIRED: 'MAX_OVERTIME_EXPIRED',
    MAPPING_WORKING_TIME_PERCENT: 'MAPPING_WORKING_TIME_PERCENT',
    SUITABLE_THRESHOLD: 'SUITABLE_THRESHOLD',
    DEFAULT_SEARCH_DISTANCE: 'DEFAULT_SEARCH_DISTANCE',
};
